
import java.io.BufferedReader;
import java.io.FileReader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author angel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    
    public Menu() {
        initComponents();
        leerarchivo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usuarios = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ganadasT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        perdidasT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        movimientosT = new javax.swing.JLabel();
        abandonadasT = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mtT = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mayorganadas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mayorperdidas = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mayorabandonos = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu mamalon");

        jLabel3.setText("Torre");

        jButton1.setText("jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });

        jButton3.setText("Registrarse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Partidas Perdidas");

        ganadasT.setText("0");

        jLabel5.setText("Partidas Ganadas");

        perdidasT.setText("0");

        jLabel7.setText("Partidas Abandonadas");

        jLabel9.setText("Movimientos Minimos");

        movimientosT.setText("000");

        abandonadasT.setText("0");

        jLabel12.setText("Tiempo:");

        mtT.setText("0:00:00");

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Jugador con mas victorias");

        mayorganadas.setText(" ");

        jLabel2.setText("Jugador con mas derrotas:");

        mayorperdidas.setText(" ");

        jLabel11.setText("Jugador con más abandonos:");

        mayorabandonos.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(96, 96, 96))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(movimientosT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ganadasT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(abandonadasT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(perdidasT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mtT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(20, 20, 20)
                                .addComponent(jButton5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mayorabandonos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel2))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mayorganadas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mayorperdidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ganadasT)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(mayorganadas))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(perdidasT)
                    .addComponent(jLabel2)
                    .addComponent(mayorperdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(abandonadasT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(movimientosT))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(mtT)))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mayorabandonos))
                        .addGap(44, 44, 44)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//estaditicas Torre de hanoi
    int pgT []=new int [5];
    int ppT[]=new int[5];
    int paT[]=new int[5];
    int mmT[]=new int[5];
    String tiempoT[]=new String[5];
    int minimohora[]=new int[5];
    int minimominuto[]= new int[5] ;
    int minimosegundo[]=new int [5];
    //estadisticas Damas
    int pgD []=new int [5];
    int ppD[]=new int[5];
    int paD[]=new int[5];
    int mmD[]=new int[5];
    String tiempoD[]=new String[5];
   
    
    //leer archivos
    public void leerarchivo(){
        
    FileReader archivo;
BufferedReader lector;
   



try {
    archivo = new FileReader("C:/Users/angel/Documents/NetBeansProjects/Proyecto2/Usuarios.txt");
    if(archivo.ready()){
        lector =new BufferedReader(archivo);
        String cadena;
        int g=0;
        int p=0;
        int a=0;
        int m=0;
        String time="";
        String nombre;
         int mh=0;
    int mm=0;
    int ms=0;
        
        
        int gD=0;
        int pD=0;
        int aD=0;
        int mD=0;
        String timeD="";
       
        
        int pp=0;
        while ((cadena=lector.readLine())!=null) {
        //asignar usuarios 
            nombre=cadena.substring(2,12);
            g=Integer.parseInt(cadena.substring(13, 15));
            p=Integer.parseInt(cadena.substring(16, 18));
            a=Integer.parseInt(cadena.substring(19, 21));
            m=Integer.parseInt(cadena.substring(22, 25));
         
            mh=Integer.parseInt(cadena.substring(26,27));
            mm=Integer.parseInt(cadena.substring(28,30));
            ms=Integer.parseInt(cadena.substring(31,33));
            
           
            gD=Integer.parseInt(cadena.substring(34, 36));
            pD=Integer.parseInt(cadena.substring(37, 39));
            aD=Integer.parseInt(cadena.substring(40, 42));
            mD=Integer.parseInt(cadena.substring(43, 46));
           timeD=cadena.substring(47,cadena.length());
           
            
            minimohora[pp]=mh;
            minimominuto[pp]=mm;
            minimosegundo[pp]=ms;
           
           pgT[pp]=g;
           ppT[pp]=p;
           paT[pp]=a;
          mmT[pp]=m;
          
            
           pgD[pp]=gD;
           ppD[pp]=pD;
           paD[pp]=aD;
           mmD[pp]=mD;
           tiempoD[pp]=timeD;
            
            
           usuarios.insertItemAt(nombre, pp);
            pp=pp+1;
        }

    }else{
        System.out.println("El archivo no esta listo para ser leido");

    }
} catch (Exception e) {
    System.out.println("Error: "+e.getMessage());
}
    
    
    }
    
    
    
    //Torre de hanoiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Torre torre1 = new Torre(this, false);
torre1.setNJ(usuarios.getSelectedIndex());
torre1.setVisible(true);



    }//GEN-LAST:event_jButton1ActionPerformed

//jugador seleccionado    
    int Jugador=0;

    public int getJugador() {
        return Jugador;
    }

    public void setJugador(int nJugador) {
        this.Jugador = nJugador;
    }
    
   
    
    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
   int pos =usuarios.getSelectedIndex();
  int mayor=0;
  int mayorp=0;
  int mayoa=0;
  int pg=0;
  int pp=0;
  int pa=0;
        for (int i = 0; i < 5; i++) {
            if(pgT[i]>mayor){
                mayor=pgT[i];
          pg=i;
          
            }
            if(ppT[i]>mayorp){
                mayorp=ppT[i];
            pp=i;
            }
            if(paT[i]>mayoa){
                mayoa=paT[i];
                pa=i;
            }
            
            
            
        }
   mayorganadas.setText(usuarios.getItemAt(pg));
   mayorperdidas.setText(usuarios.getItemAt(pp));
   mayorabandonos.setText(usuarios.getItemAt(pa));
   
   int h=minimohora[pos];
   int m=minimominuto[pos]-10;
   int s=minimosegundo[pos]-10;
   Jugador=pos;
   ganadasT.setText(String.valueOf(pgT[pos]-10));
   perdidasT.setText(String.valueOf(ppT[pos]-10));
   abandonadasT.setText(String.valueOf(paT[pos]-10));
   movimientosT.setText(String.valueOf(mmT[pos]-100));
   mtT.setText(h+":"+m+":"+s);
   
    }//GEN-LAST:event_usuariosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        //registrar jugadores
        Registro regitracion =new Registro (this, false);
        regitracion.setVisible(true);
  
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
try {
            usuarios.removeAllItems();
        } catch (Exception e) {
            
            leerarchivo();
        }
       
     
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abandonadasT;
    private javax.swing.JLabel ganadasT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel mayorabandonos;
    private javax.swing.JLabel mayorganadas;
    private javax.swing.JLabel mayorperdidas;
    private javax.swing.JLabel movimientosT;
    private javax.swing.JLabel mtT;
    private javax.swing.JLabel perdidasT;
    private javax.swing.JComboBox<String> usuarios;
    // End of variables declaration//GEN-END:variables
}
